import { Metadata } from "next";
import ContactCard from "@/components/Legal/ContactCard";
import PrivacyList from "@/components/Privacy/PrivacyList";
import PrivacySection from "@/components/Privacy/PrivacySection";
import PrivacyBoldList from "@/components/Privacy/PrivacyBoldList";
import Link from "next/link";
export const metadata: Metadata = {
  title: "Privacy Policy | BrosBrain Ltd",
  description: "Privacy Policy of BrosBrain Ltd",
};

const personalInfo = [
  "Full Name",
  "Email Address",
  "Phone Number",
  "Address, State, Province, ZIP/Postal code, City",
  "Usage Data",
];

const Cookies1 = [
  {
    title: "Cookies or Browser Cookies",
    description: "A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.",
  },
  {
    title: "Web Beacons",
    description: "Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).",

  }
];
const Cookies2 = [
  {
    title: "Necessary / Essential Cookies",
    description: "Type: Session Cookies\n Administered by:Us \nPurpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services. Cookies Policy / Notice Acceptance Cookies",
  },
  {
    title: "Cookies Policy / Notice Acceptance Cookies",
    description: "Type: Persistent Cookies \n Administered by: Us \nPurpose: These Cookies identify if users have accepted the use of cookies on the Website.",
  }, {
    title: "Functionality Cookies",
    description: "Type: Persistent Cookies \n Administered by: Us \nPurpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.",
  }
];
const Definitions_list = [
  {
    title: "Account",
    description: "means a unique account created for You to access our Service or parts of our Service.",
  },
  {
    title: "Affiliate",
    description: 'means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.',
  },
  {
    title: "Company",
    description: '(referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Brosbrain Inc, 618 Washwood Heath Rd, Birmingham, B82 HG, United Kingdom.',
  },
  ,
  {
    title: "Cookies",
    description: " are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.",
  }
  ,
  {
    title: "Country",
    description: "refers to: Birmingham, United Kingdom",
  }
  ,
  {
    title: "Device",
    description: "means any device that can access the Service such as a computer, a cellphone or a digital tablet.",
  }
  ,
  {
    title: "Personal Data",
    description: "is any information that relates to an identified or identifiable individual.",
  }
  ,
  {
    title: "Service",
    description: "refers to the Website.",
  },
  {
    title: "Service Provider",
    description: "means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.",
  },
  {
    title: "Usage Data ",
    description: "refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).",
  },
  {
    title: "Website",
    description: "refers to Brosbrain, accessible from https://brosbrain.com",
  },
  {
    title: "You",
    description: "means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.",
  },
];
const uses = [{
  title: "To provide and maintain our Service",
  description: "including to monitor the usage of our Service.",
},
{
  title: "To manage Your Account",
  description: "to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.",
}, {
  title: "For the performance of a contract:",
  description: "the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.",
}, {
  title: "To contact You",
  description: "To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.",
}, {
  title: "To provide You",
  description: "with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.",
}, {
  title: "To manage Your requests:",
  description: "To attend and manage Your requests to Us.",
}, {
  title: "For business transfers",
  description: "We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.",
}, {
  title: "For other purposes",
  description: "We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.",
},
];
const uses2 = [{
  title: "With Service Providers",
  description: " We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You.",
}, {
  title: "For business transfers",
  description: "We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.",
}, {
  title: "With Affiliates",
  description: " We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.",
}, {
  title: "With other users",
  description: "when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.",
}, {
  title: "With Your consent",
  description: "We may disclose Your personal information for any other purpose with Your consent.",
},
]
const legalList = [
  "Comply with a legal obligation",
  "Protect and defend the rights or property of the Company",
  "Prevent or investigate possible wrongdoing in connection with the Service",
  "Protect the personal safety of Users of the Service or the public",
  "Protect against legal liability",
];

const rights = [
  "Access your personal data",
  "Correct inaccurate information",
  "Request deletion",
  "Restrict processing",
  "Object to processing",
  "Request data portability",
  "Withdraw consent",
];

export default function PrivacyPolicyPage() {
  return (
    <section className="pt-[120px] pb-[120px]">
      <div className="container">
        <h1 className="mb-4 text-4xl font-bold">
          Privacy Policy
        </h1>

        <p className="mb-8 text-black dark:text-white leading-8">
          Last updated: September 28, 2023
        </p>

        <p className="mb-10 text-black dark:text-white leading-8">
          This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
          We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the {" "}
          <Link href="https://www.privacypolicies.com/privacy-policy-generator/" className="text-blue-600 underline"> Privacy Policy Generator
          </Link>
        </p>

        <PrivacySection title="Interpretation and Definitions">
          <h3 className="text-xl font-semibold text-black dark:text-white">
            Interpretation
          </h3>
          <p className="mb-10 text-black dark:text-white leading-8">
            The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
          </p>
          {/* <PrivacyList items={personalInfo} /> */}

          <h1 className="text-xl font-semibold text-black dark:text-white">
            Definitions
          </h1>
          <p className=" text-black dark:text-white leading-8">
            For the purposes of this Privacy Policy:
          </p>
          <PrivacyBoldList items={Definitions_list} />
        </PrivacySection>

        <PrivacySection title="Collecting and Using Your Personal Data">
          <h1 className="text-xl font-semibold text-black dark:text-white">
            Types of Data Collected
          </h1>
          <h3 className="text-x font-bold text-black dark:text-white">
            Personal Data
          </h3>
          <p className=" text-black dark:text-white leading-8">
            While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
          </p>
          <PrivacyList items={personalInfo} />
          <h3 className="text-x font-bold text-black dark:text-white">
            Usage Data
          </h3>
          <p className=" text-black dark:text-white leading-8">
            Usage Data is collected automatically when using the Service.<br />

            Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.<br />

            When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.<br />

            We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.
          </p>
          <h3 className="text-x font-bold text-black dark:text-white">
            Tracking Technologies and Cookies
          </h3>
          <p className=" text-black dark:text-white leading-8">
            We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:
          </p>
          <PrivacyBoldList items={Cookies1} />
          <p>Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser. Learn more about cookies on the <Link href="https://www.privacypolicies.com/blog/privacy-policy-template/#Use_Of_Cookies_Log_Files_And_Tracking" className="text-blue-500 hover:underline">Privacy Policies Website</Link>  article.</p>
          <p>We use both Session and Persistent Cookies for the purposes set out below:</p>
          <PrivacyBoldList items={Cookies2} />
          <p>For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.</p>

          <h1 className="text-xl font-semibold text-black dark:text-white">
            Use of Your Personal Data
          </h1>
          <p>The Company may use Personal Data for the following purposes:</p>
          <PrivacyBoldList items={uses} />
          <p className="text-black font-bold dark:text-white leading-8">
            No mobile information will be shared with third parties/affiliates for marketing/promotional purposes. All the above categories exclude text messaging originator opt-in data and consent; this information will not be shared with any third parties
          </p>
          <p>We may share Your personal information in the following situations:</p>

          <PrivacyBoldList items={uses2} />
          <h1 className="text-xl font-semibold text-black dark:text-white">
            Retention of Your Personal Data
          </h1>
          <p>
            The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
          </p>
          <p>
            The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.
          </p>

          <h1 className="text-xl font-semibold text-black dark:text-white">
            Transfer of Your Personal Data
          </h1>
          <p>Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.</p>
          <p>Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.</p>
          <p>The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.</p>

          <h1 className="text-xl font-semibold text-black dark:text-white">
            Delete Your Personal Data
          </h1>
          <p>You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.</p>
          <p>Our Service may give You the ability to delete certain information about You from within the Service.</p>
          <p>You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.</p>
          <p>Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.</p>
        </PrivacySection>

        <PrivacySection title="Disclosure of Your Personal Data">

          <h3 className="text-x font-bold text-black dark:text-white">
            Business Transactions
          </h3>
          <p>
            If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.
          </p>

          <h3 className="text-x font-bold text-black dark:text-white">
            Law enforcement
          </h3>
          <p>Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>
          <h3 className="text-x font-bold text-black dark:text-white">
            Other legal requirements
          </h3>
          <p>The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
          <PrivacyList items={legalList} />

          <h3 className="text-xl font-bold text-black dark:text-white">
            Security of Your Personal Data
          </h3>
          <p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
          </p>
        </PrivacySection>

        <PrivacySection title="SMS Terms & Conditions">
          <p>Product Description By providing your mobile phone number, you consent to receive SMS messages from Brosbrain related to project status updates, meeting and call reminders, support and service notifications, deployment alerts, and important updates regarding product releases or deadlines. Message Frequency (use whichever matches the submission in the registration form) Message frequency may vary. You may receive 10 SMS messages per week. Message and Data Rates Standard message and data rates may apply. Opting Out You may opt out of receiving SMS messages at any time by replying with "STOP" to any SMS message you receive from us. After opting out, you will receive a confirmation message, and we will cease sending SMS messages to your number. Help and Support If you need assistance or have questions about our SMS service, reply with "HELP" to any SMS message you receive, or contact our customer support team at +44 745 536 6977. Privacy Policy Your phone number will be handled in accordance with our Privacy Policy, available at <Link href="/privacy" className="text-blue-500 hover:underline">Privacy Policy</Link>. No mobile information will be shared with third parties/affiliates for marketing/promotional purposes. All the above categories exclude text messaging originator opt-in data and consent; this information will not be shared with any third parties.</p>
        </PrivacySection>

        <PrivacySection title="Children's Privacy">
          <p>
            Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.
          </p>
          <p>If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.</p>
        </PrivacySection>

        <PrivacySection title="Links to Other Websites">
          <p>
            Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.
          </p>
          <p>
            We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
          </p>
        </PrivacySection>

        <PrivacySection title="Changes to this Privacy Policy">
          <p>
            We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.
          </p>
          <p>We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.
          </p>
          <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
        </PrivacySection>





        <PrivacySection title="Contact Us">
          <p>If you have any questions about this Privacy Policy, You can contact us:</p>
          <ContactCard />
        </PrivacySection>
      </div>
    </section>
  );
}